export const EMAIL_TEMPLATE_NAMES = {
  ACTIVATE_USER: 'ACTIVATE_USER',
  FORGOT_PASSWORD_USER: 'FORGOT_PASSWORD_USER',
  RESET_PASSWORD_USER: 'RESET_PASSWORD_USER',
  ACCEPTED_OFFER_OFFER: 'ACCEPTED_OFFER_OFFER',
  REFUSED_OFFER_OFFER: 'REFUSED_OFFER_OFFER',
  INSERT_OFFER_OFFER: 'INSERT_OFFER_OFFER',
  ROUTE_CREATE: "ROUTE_CREATED",
};
